# labels:
#   backend: local

# pipeline:
# - name: Test commands
#   image: bash
#   commands:
#     - echo $RUNTIME_DIRECTORY  
#     - echo "HELLO WORLD"
#     - echo $HOME
#     - pwd
#     - nix --version
#     - nix doctor
#     - nix store ping  
#     - whereis nix
#     - which nix
#     - nix run 'nixpkgs#hello'
#     - ls -la $HOME
#     - ls -la $HOME/.cache
#     - ls -la
#     - ls -la .cache
#     - nix flake show
#     - nix run


